spring:
  application:
    name: api-gateway

  config:
    # import: optional:configserver:http://localhost:8888
    import: "optional:configserver:"
  cloud:
    config:
      uri:
      - http://localhost:8888

  profiles:
    active: local
